import type { Role } from "./types"

/** Newest first. Source of truth for the site; mirror changes to LinkedIn. */
export const experience: Role[] = [
  {
    company: "Cisco",
    title: "Senior Software Engineer, Team Lead",
    location: "San José, Costa Rica",
    start: "2024-01",
    summary: "Internal tools that keep departments on track with software lifecycle and security compliance.",
    highlights: [
      "Ship features for new and existing internal tools using AI-assisted development with Claude, Cursor, and Copilot.",
      "Trained models on internal knowledge so teams can query it directly.",
    ],
    stack: ["Claude", "Cursor", "Copilot", "LLMs"],
  },
  {
    company: "MyndsIT",
    title: "Founder, Software Engineer",
    location: "Alajuela, Costa Rica",
    start: "2014-01",
    summary: "My studio for client work and my own products across web and mobile.",
    highlights: [
      "Deliver full-stack web and mobile applications for clients.",
      "Build and run my own SaaS products, including Travelix, Mobifactura, Rentivo, and Orvis.",
      "Use new products to pick up unfamiliar stacks and stay current.",
    ],
    stack: ["React", "React Native", "NestJS", "Firebase", "PostgreSQL"],
  },
  {
    company: "DrChrono by EverHealth",
    title: "Senior Software Engineer",
    start: "2024-02",
    end: "2026-06",
    summary: "Payments team for the DrChrono and onpatient healthcare applications.",
    highlights: ["Built and maintained payment features across web and mobile clients."],
    stack: ["Django", "Python", "React", "React Native", "JavaScript"],
  },
  {
    company: "Tone",
    title: "Senior Software Development Engineer",
    location: "Remote, United States",
    start: "2022-06",
    end: "2024-02",
    summary: "Royalties platform that helps music labels pay their artists accurately and on time.",
    highlights: [
      "Reworked the notification system so client notifications were accurate.",
      "Integrated payment providers such as Wise for royalty payouts.",
      "Raised test coverage to 90% across several areas of the app.",
      "Built customer-facing insights dashboards with the data team.",
    ],
    stack: ["Python", "Django", "PostgreSQL", "TypeScript", "React"],
  },
  {
    company: "Riparian LLC",
    title: "Senior Full-Stack Software Engineer",
    location: "Remote, United States",
    start: "2020-03",
    end: "2022-05",
    summary: "Helix and Ion, calculation-heavy platforms with a TypeScript API, workers, and Vue front end.",
    highlights: [
      "Improved performance and stability by redesigning how calculations run, moving them to asynchronous workers.",
      "Migrated the front end to a new Vue.js version for a better user experience.",
    ],
    stack: ["TypeScript", "Node.js", "Express", "Vue.js"],
  },
  {
    company: "American Kennel Club",
    via: "3Pillar Global",
    title: "Senior Software Development Engineer",
    location: "Costa Rica",
    start: "2018-02",
    end: "2020-02",
    summary: "Internal and public applications REGIS, BRETT, and JPM.",
    highlights: [
      "Built features across Python microservices feeding Angular and React front ends.",
      "Worked with MongoDB, Oracle, and Redis for high-throughput data.",
      "Helped plan sprints and took part in architecture decisions.",
    ],
    stack: ["Python", "Angular", "React", "MongoDB", "Oracle", "Redis"],
  },
  {
    company: "Stream Energy",
    title: "Senior Software Engineer, Consultant",
    location: "Dallas, Texas",
    start: "2017-07",
    end: "2018-02",
    summary: "On-site contractor improving the billing notification system.",
    highlights: ["Learned the billing process from the business side to automate it and apply best practices."],
    stack: ["PHP", "CodeIgniter", "JavaScript", "SQL Server"],
  },
  {
    company: "DXC Technology",
    title: "Software Engineer Team Lead",
    location: "Heredia, Costa Rica",
    start: "2017-01",
    end: "2017-07",
    summary: "Automation of billing processes.",
    highlights: [
      "Formed a Scrum team that automated repetitive billing work and freed up staff time.",
      "Led a multinational team across India, Bulgaria, the United States, and Costa Rica.",
      "Evaluated and recommended RPA technologies based on business needs.",
    ],
    stack: ["RPA", "Scrum", "Automation"],
  },
  {
    company: "Fiserv",
    title: "Software Engineer",
    location: "Heredia, Costa Rica",
    start: "2013-08",
    end: "2017-01",
    summary: "Core banking application for the Latin America, Caribbean, and Canada clients team.",
    highlights: [
      "Specialized in the security subsystem protecting critical financial data.",
      "Trained new hires on the stack and led continuous-improvement projects.",
      "Started in technical support, implementing client change requests in RPGLE and CLLE.",
      "Helped roll out ServiceNow as the team's ticketing tool.",
    ],
    stack: ["RPGLE", "CLLE", "IBM i", "ServiceNow"],
  },
]
