import type { Project } from "./types"

/**
 * Every project, newest first within each group.
 * Private repositories are listed without a `repo` link on purpose.
 */
export const projects: Project[] = [
  {
    slug: "travelix",
    name: "Travelix",
    summary: "Collaborative trip planning and expense tracking for friend groups.",
    start: 2023,
    ongoing: true,
    org: "MyndsIT",
    role: "Founder",
    stack: ["React", "Capacitor", "Firebase", "TypeScript", "Flutter"],
    site: "https://travelix.app",
    screenshot: "/projects/travelix.jpg",
    featured: true,
    details: [
      "Travelix is where a friend group plans a trip and settles the tab: shared itineraries, expenses split as you go, and balances everyone can see.",
      "It shipped on Google Play first as a Flutter app with a Node.js and Firebase backend. Version 2 is a rewrite in React 19, Vite, and Tailwind wrapped with Capacitor, with a shared core package for the Firestore data layer so web and mobile share one codebase.",
      "AI now helps track expenses and plan the trip itself.",
    ],
  },
  {
    slug: "rentivo",
    name: "Rentivo",
    summary: "Property management for landlords: tenants, leases, buildings, payments, and notifications in one dashboard.",
    start: 2026,
    ongoing: true,
    org: "MyndsIT",
    role: "Founder",
    stack: ["Expo", "React Native", "Supabase", "Next.js", "Node.js"],
    site: "https://gorentivo.com",
    screenshot: "/projects/rentivo.jpg",
    featured: true,
    details: [
      "Rentivo is a multi-tenant property management platform. Companies invite their team under six roles, from company admin and property manager to finance, maintenance, and tenants, and users can belong to and switch between several companies.",
      "Data isolation between companies is enforced in the database with Postgres row-level security on Supabase, and real-time subscriptions keep every client up to date.",
      "Gativo, a companion Node.js TCP server, reads RFID tags from any TCP or HTTP capable reader, validates them against approved tags, and triggers webhooks for building access.",
    ],
  },
  {
    slug: "mobifactura",
    name: "Mobifactura",
    summary: "Electronic invoicing SaaS for Costa Rica, compliant with Ministerio de Hacienda v4.4.",
    start: 2019,
    ongoing: true,
    org: "MyndsIT",
    role: "Founder",
    stack: ["React", "TanStack Router", "Tailwind", "Firebase", "Cloud Functions"],
    site: "https://mobifactura.web.app",
    screenshot: "/projects/mobifactura.jpg",
    featured: true,
    details: [
      "Mobifactura wraps Costa Rica's e-invoicing pipeline into a web-first product. Issuers create invoices, the backend signs the XML, submits it to Hacienda, and handles the callback, then renders the PDF and a public QR viewer for each invoice.",
      "The current version is a monorepo with a Vite and React front end, Firebase Cloud Functions, and shared TypeScript models for the v4.4 spec. Each side deploys independently from CI when its paths change.",
      "Earlier versions were built in Angular and Flutter.",
    ],
  },
  {
    slug: "orvis",
    name: "Orvis",
    summary: "Free TV and radio streaming apps for Costa Rica and China.",
    start: 2020,
    ongoing: true,
    org: "MyndsIT",
    role: "Founder",
    stack: ["React", "Capacitor", "Firebase", "HLS", "i18next"],
    site: "https://orvisapp.web.app",
    links: [
      { label: "Google Play · Costa Rica", href: "https://play.google.com/store/apps/details?id=com.orvis.crc" },
      { label: "Google Play · China", href: "https://play.google.com/store/apps/details?id=com.mlopezitsolutions.chinatv" },
    ],
    // Composed from the Google Play store screenshots (not reproducible with `pnpm screenshots`).
    screenshot: "/projects/orvis.jpg",
    featured: true,
    details: [
      "Orvis is a small family of free streaming apps that bring live TV and radio from Costa Rica, Nicaragua, and China to one place.",
      "One React and Vite web app is wrapped with Capacitor into a separate store app per country. Shared packages hold the data layer, per-country configuration, HLS stream probing, and translations, with Firebase Cloud Functions and Firestore behind them.",
      "It replaced two separate Expo apps with a single codebase.",
    ],
  },
  {
    slug: "mangai",
    name: "mangAI",
    summary: "Turns English manga pages into audio stories with separate narrator and character voices.",
    start: 2025,
    stack: ["Python", "GPT-4 Vision", "OpenAI", "ElevenLabs"],
    site: "https://imrlopez.github.io/mangAI/",
    repo: "https://github.com/iMrLopez/mangAI",
    screenshot: "/projects/mangai.jpg",
    featured: true,
    details: [
      "Upload a manga page and mangAI reads the panels with GPT-4 Vision, writes a script with GPT-4, and voices it with ElevenLabs multi-voice text-to-speech, giving the narrator and each character a distinct voice.",
    ],
  },
  {
    slug: "wattsup",
    name: "WattsUp",
    summary: "Estimates how much charging an electric vehicle adds to your electricity bill.",
    start: 2025,
    stack: ["Python", "FastAPI", "Prolog", "Next.js", "PostgreSQL", "Docker"],
    repo: "https://github.com/iMrLopez/WattsUp",
    featured: true,
    details: [
      "WattsUp combines rule-based Prolog inference with machine learning. Prolog rules estimate the energy a charging session needs from battery capacity, vehicle age, and duration, and the API prices it against real Costa Rican tariffs by company and period.",
      "Prolog facts are seeded from PostgreSQL at runtime, and a Next.js front end lets you try estimates interactively.",
    ],
  },

  {
    slug: "smartcontrol",
    name: "SmartControl",
    summary: "Fleet management app for tracking vehicles, assignments, maintenance, and fuel spend.",
    start: 2026,
    org: "MyndsIT",
    stack: ["React Native", "Expo", "TypeScript"],
  },
  {
    slug: "crgyms",
    name: "CRGyms",
    summary: "Searchable directory of gyms, CrossFit boxes, and fitness studios across Costa Rica.",
    start: 2026,
    org: "MyndsIT",
    stack: ["Next.js", "TypeScript"],
  },
  {
    slug: "gativo",
    name: "Gativo",
    summary: "Universal RFID TCP server that validates tags and fires webhooks, built for Rentivo.",
    start: 2026,
    stack: ["Node.js", "TCP"],
    repo: "https://github.com/iMrLopez/Gativo",
  },
  {
    slug: "headunit-adb-scripts",
    name: "Head unit ADB installer",
    summary: "Installs Android apps on car head units over Wi-Fi from a curated catalog.",
    start: 2026,
    stack: ["PowerShell", "ADB"],
    site: "https://imrlopez.github.io/headunit-adb-scripts/",
    repo: "https://github.com/iMrLopez/headunit-adb-scripts",
  },
  {
    slug: "simple-pinball",
    name: "Simple Pinball",
    summary: "A small pinball game.",
    start: 2026,
    stack: ["Godot", "GDScript"],
    repo: "https://github.com/iMrLopez/Simple-Pinball",
  },
  {
    slug: "android-auto-geely",
    name: "Android Auto for Geely",
    summary: "Script to enable Android Auto on Geely cars.",
    start: 2024,
    stack: ["Shell", "ADB"],
    repo: "https://github.com/iMrLopez/android-auto-carplay-geely",
  },
  {
    slug: "mushroom-cards-animations",
    name: "Mushroom card animations",
    summary: "Animations for Home Assistant's Mushroom cards, shared with the community.",
    start: 2024,
    stack: ["Home Assistant"],
    repo: "https://github.com/iMrLopez/mushroom_cards_animations",
  },
  {
    slug: "tone",
    name: "Tone royalties platform",
    summary: "Notifications, Wise payouts, 90% test coverage, and insights dashboards for a music royalties platform.",
    start: 2022,
    end: 2024,
    org: "Tone",
    stack: ["Django", "PostgreSQL", "React", "TypeScript"],
  },
  {
    slug: "covid-qr-decoder",
    name: "Costa Rica COVID QR decoder",
    summary: "Decodes the Ministerio de Salud vaccination QR codes.",
    start: 2021,
    stack: ["Node.js"],
    repo: "https://github.com/iMrLopez/Decode_MinisterioSaludCR_QR_COVID_Node",
  },
  {
    slug: "interview-tests",
    name: "Interview tests",
    summary: "Technical tests for interviewing candidates, organized by technology and seniority.",
    start: 2021,
    stack: ["Various"],
    repo: "https://github.com/iMrLopez/Interview-tests",
  },
  {
    slug: "esemenu",
    name: "EseMenu",
    summary: "QR code menus for restaurants, with an admin app for managing them.",
    start: 2019,
    end: 2021,
    org: "MyndsIT",
    stack: ["Firebase", "Angular", "Flutter"],
  },
  {
    slug: "isthmus-learning",
    name: "Isthmus Learning v2",
    summary: "Training program teaching developers current technologies.",
    start: 2019,
    end: 2020,
    stack: ["AngularJS"],
  },
  {
    slug: "asefiserv",
    name: "AseFiserv IT stack",
    summary: "Planned and ran the full IT stack, from equipment to a new website.",
    start: 2016,
    end: 2018,
    org: "MyndsIT",
    stack: ["IT management", "Web"],
  },
  {
    slug: "cobro-agil",
    name: "Cobro Ágil IT stack",
    summary: "Responsive WordPress site, email, and cloud storage administration.",
    start: 2016,
    end: 2017,
    org: "MyndsIT",
    stack: ["WordPress", "IT management"],
  },
  {
    slug: "servicenow-fiserv",
    name: "ServiceNow rollout",
    summary: "Data migration, QA, and user training for the move to ServiceNow ITIL ticketing.",
    start: 2016,
    end: 2017,
    org: "Fiserv",
    stack: ["ServiceNow", "Scrum"],
  },
  {
    slug: "lot-management-system",
    name: "Lot management system",
    summary: "Web app tracking incoming and outgoing lots for Tico Electronics.",
    start: 2014,
    end: 2015,
    stack: ["PHP", "MySQL", "JavaScript"],
  },
  {
    slug: "point-of-sale",
    name: "Point of sale system",
    summary: "Custom POS for tracking sales to internal staff.",
    start: 2014,
    end: 2015,
    stack: ["PHP", "MySQL", "JavaScript"],
  },
]

export const featuredProjects = projects.filter((p) => p.featured)
export const projectsWithPages = projects.filter((p) => p.details?.length)
