// Generates the GitHub profile README.md from content/, so the profile and
// marnylopez.com never drift apart. CI fails if README.md is out of date.
//
//   pnpm readme
import { writeFile } from "node:fs/promises"
import { join } from "node:path"

import { toolbox } from "../content/education"
import { experience } from "../content/experience"
import { profile } from "../content/profile"
import { featuredProjects } from "../content/projects"
import { resources } from "../content/resources"
import { formatRange, projectRange } from "../lib/format"

const site = profile.site
const link = (label: string, href: string) => `[${label}](${href})`

const current = experience
  .filter((role) => !role.end)
  .map((role) => `- ${role.title} at **${role.company}** (${formatRange(role.start, role.end)})`)

const work = featuredProjects.map(
  (p) =>
    `| ${link(p.name, `${site}/projects/${p.slug}/`)} | ${p.summary} | ${p.stack.slice(0, 4).join(" · ")} | ${projectRange(p)} |`,
)

const videos = resources
  .filter((r) => r.href)
  .map((r) => `- ${link(r.title, r.href!)} · ${r.year ?? ""} · ${r.language.toUpperCase()}`)

const readme = `<!-- Generated by scripts/readme.ts from content/. Edit content/ and run \`pnpm readme\`, not this file. -->

# ${profile.name}

**${profile.headline}** · ${profile.location}

${profile.lede}

${[link("marnylopez.com", site), link("LinkedIn", profile.linkedin), link("YouTube", profile.youtube)].join(" · ")}
${profile.availableForWork ? `\n> Available for new work. ${link("Message me on LinkedIn", profile.linkedin)}.\n` : ""}
### Currently

${current.join("\n")}

### Selected work

| Project | What it is | Stack | When |
|---|---|---|---|
${work.join("\n")}

More projects and full experience on ${link("marnylopez.com", site)}.

### Toolbox

${toolbox.map((group) => `**${group.area}:** ${group.items.join(", ")}`).join("  \n")}

### Videos

${videos.join("\n")}

---

<sub>This repository also builds ${link("marnylopez.com", site)}. See ${link("docs/DEVELOPMENT.md", "docs/DEVELOPMENT.md")}.</sub>
`

await writeFile(join(process.cwd(), "README.md"), readme)
console.log("✓ README.md")
